postgresql:
  enabled: true
  auth:
    username: wfp
    password: wfp_secret
    database: wfp

rabbitmq:
  enabled: true
  auth:
    username: wfp
    password: wfp_secret

keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: admin
