replicaCount: 1

image:
  repository: wfp/workflow-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.1"
