replicaCount: 1

image:
  repository: wfp/custom-fields-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70

env: {}
