apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    app: {{ include "chart.fullname" . }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:{{ .Values.service.grpcPort }}"
          http:
            endpoint: "0.0.0.0:{{ .Values.service.httpPort }}"

    processors:
      batch:
        timeout: 5s
        send_batch_size: 512
      memory_limiter:
        check_interval: 1s
        limit_mib: 400
        spike_limit_mib: 100

    exporters:
      googlecloud:
        project: {{ .Values.gcpProjectId | quote }}

    service:
      telemetry:
        logs:
          level: warn
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [googlecloud]
